# GitHub Sponsors configuration for OntoGuard
#
# This file enables the "Sponsor" button on the repository,
# making it easier for users to support the project financially.
#
# For more details, see: https://docs.github.com/en/github/administering-a-repository/configuring-github-sponsors-for-your-repository

github: [cloudbadal007] # GitHub username for GitHub Sponsors

# Optional: Add other funding platforms
# patreon: your-patreon-name
# open_collective: your-open-collective-name
# ko_fi: your-ko-fi-name
# tidelift: npm/tidelift-lib
# community_bridge: # Replace with a community bridge project name e.g., 'cloud-foundry'
# liberapay: your-liberapay-name
# issuehunt: your-issuehunt-name
# custom: ["https://www.example.com/donate", "https://www.example.com/support-us"]

# Note: Supporting this project helps us maintain and improve OntoGuard,
# ensuring a robust semantic firewall for AI agents. Thank you for your support!
